# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_user_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_activity', to='login_app.User')),
            ],
        ),
    ]
